name: Print Step Data

on: [push]

jobs:
  print-step-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Use Node
        uses: actions/setup-node@v2
      
      - id: install-dependencies
        name: Install dependencies
        run: npm install
      
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      
      - name: Log step time
        run: echo '${{ steps.print-name-step.outputs.time }}'
      
      - name: Dump print-name-step step
        run: echo '${{ toJson(steps.print-name-step) }}'