name: Simple Matrix

on: [push]

jobs:
  print-node-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [14, 15, 16]
    steps:
      - name: Print Node version
        run: node -v